global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'fl_server'
    static_configs:
      - targets: ['fl_server:5000']
    metrics_path: '/metrics'
    scrape_interval: 5s

  - job_name: 'pushgateway'
    honor_labels: true
    static_configs:
      - targets: ["fl_pushgateway:9091"]
